# Introduction

Currently, detection of early stage ovarian cancer is limited by the current screening landscape. As a result, most ovarian cancer is not diagnosed until later stages, with about 80% of ovarian cancer cases diagnosed in stage 3 or greater<sup>1</sup>. Early intervention of ovarian cancer, when detected in earlier stages, leads to better patient outcomes<sup>1</sup>. 
In tandem with developments of more sensitive biological screening tests, researchers are curious if patterns in clinical documentation, leading to the cancer diagnosis may contain distinct patterns. If patterns are found in clinical notes, various types of machine learning algorithms may help provide tools or insight to clinicians to identify early risk for ovarian cancer. 
Additional to a lack of screening tool, early symptoms of ovarian cancer are understood to be broad and unspecific, fatigue and abdominal bloating<sup>2</sup>. Exploring both supervised and unsupervised learning models will allow us to explore machine learning as a tool, in the case of an unsupervised model, or expanded insight, alongside a tool, in the case of a supervised model. If we can create a successful supervised machine learning model, model specifications of distinct clinical features found to be associative with the outcome may also build clinical understanding of symptomology<sup>3</sup>. 
