# Conclusions

While vectorization could have provided an ideal solution to find novel symptoms, risk factors or patterns of behavior in clinical notes of patients with ovarian cancer, directly relating to new understanding of early disease progression, our results show this approach is quite noisy and struggles to yield clear and meaningful results. Eventual clustering of phrases on themes was able to draw out a few patterns. Notably, phrases referring to divorce, swelling, smoking, cardiac events and nausea, provide future hypotheses to be expanded upon and empirically tested in future research. Current results fail to include appropriate context of key phrases, as they relate to clustered themes, limiting meaningfulness. For example, phrases indicating "divorce" does not differentiate between a previous, on-going or non-occurring event. 

Our second method, embedding of clinical notes and use in a Random Forest model, yielded poor results as well. Accuracy of these models ranged from 55-59%, which is barely better than random chance. These conclusions could be due to adjustments required in methodology. It is possible the pre-trained embedding model applied to these notes was not the best embedding model for this data. The model was suggested because more general models, such as BioBERT, were not available to me, due to institutional limitations. Additionally, classification occurred at the notes level, not the patient or visit level. It is possible an approach that aggregates embedded values into more contextual groupings, such as visits, could provide more robust units of analysis. One possible method to achieve this may be box embedding<sup>14</sup>. It is also possible, there is not a clear prediction signal in the clinical notes to predict subsequent ovarian cancer diagnosis. There are multiple additional methodologies that should be applied before this conclusions is taken, given the limitations of this analysis. 

Our analysis is limited greatly by scope, which did not explore deep learning models or the inclusion of structured features, such as medication or diagnosis information alongside unstructured data. Natural future steps would be to implement both, starting with the integration of the structured features. Future analyses would benefit from maintaining optimally parsimonious models, so insight in source of prediction could be understood and applied to clinical practice. 
