# Introduction

Ovarian cancer is the fifth most common cause of cancer deaths among women in the United States, given only about 52% of women diagnosed with ovarian cancer survive 5 years after diagnosis<sup>1</sup>. This is due, in large part, to the lack of an effective screening test for ovarian cancer and limited symptoms in early disease. As a result, most ovarian cancer is not diagnosed until later stages, with about 80% of ovarian cancer cases diagnosed in stage 3 or greater<sup>2</sup>. Early detection of ovarian cancer leads to better patient outcomes, including longer stage-adjusted survival rates<sup>2</sup>. 

In tandem with developments of effective biologic-based screening tests, ovarian cancer advocates are curious whether clinical documentation leading up to diagnosis contains distinct patterns. Previous methods, based traditional statistical models, may have missed a distinct symptom or risk factor. If patterns are found in clinical notes, various types of machine learning algorithms may help provide tools or insight to clinicians to identify early risk for ovarian cancer. 

Though symptoms in early stages of ovarian cancer tend to be vague, some patterns in literature and clinical care have emerged, such as fatigue and abdominal bloating<sup>3</sup>. This provides optimism that patterns may highlight early symptoms not yet identified. Models using vectorization and embedding will provide different tools for understanding patterns. In the case of vectorized models, some power to connect similarity between features may be lost but ease of interpretation of results in clinical practice remains high. Conversely, embedding-based models increase capacity to measure similarity between observations but at the cost of reduced generalizability<sup>4</sup>. 
